config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#index"

  resources :pages
  

  
end

app/models/page.rb
class Page < ActiveRecord::Base
validates :post, length:{in: 2..200}, presence: true
validates :comment, length:{maximum: 200}, allow_nil: true

validates :user_id, presence: true
belongs_to :user

paginates_per 5
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

has_many :posts

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_page, only: [:show, :edit, :update, :destroy]

  def index
    @pages = Page.all
    @pages = Page.order(:post).page params[:page]
  end

  def new
    @page = Page.new
  end

  def create
    @page = Page.new(page_params)
    if @page.save 
      redirect_to root_path
    else
      redirect_to new_page_path
    end
  end

  def edit
  end

  def update
    @page.update(page_params)
    redirect_to root_path
  end

  def destroy
    @page.destroy
    redirect_to root_path
    
  end

private
def set_page
  @page = Page.find(params[:id])
end

def page_params
  params.require(:page).permit(:post, :comment)
end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Starter Template for Bootstrap</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <%= javascript_include_tag "https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js", "https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js" %>
  <![endif]-->

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="log_out">
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>
</div>
  <div class="navbar navbar-inverse navbar-fixed-top">

    <div class="container">

      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "Chat Box", "#", :class => "navbar-brand" %>
      </div>

        <p class="navbar-text pull-right">

      <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li class="active"><a href="#">Home</a></li>
        </ul>
      </div>
    </div>
  </div>
  <div class="container">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, :class => "alert alert-#{ name == :error ? "danger" : "success" } alert-dismissable" do %>
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <%= msg %>
      <% end %>
    <% end %>

<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>
    <%= yield %>
  </div>
</body>
</html>

app/views/pages/edit.html.erb
<br><br>

<%= form_for @page do |f| %>
<%= f.label :Post %>
<%= f.text_field :post %><br>
<%= f.text_area :comment %>
<%= f.submit %>
<% end  %><br>

app/views/pages/index.html.erb
<%= paginate @pages %><br>
<% @pages.each do |page| %>
  <%=page.post %>---

  <%=page.comment %> <%=link_to "Edit", edit_page_path(page.id)%> <%=link_to "Delete", page_path(page.id),method: :delete, data: {confirm: "Are you sure you want to delete?"}%><br>

<%end%><br>

<%=link_to "Create New Post", new_page_path%>

app/views/pages/new.html.erb
<br><br>

<%= form_for @page do |f| %>
<%= f.label :Post %>
<%= f.text_field :post %><br>
<%= f.text_area :comment, placeholder: "Comment" %>
<%= f.submit %>
<% end  %><br>